### PR TITLE
Implement update of snapshot while it deleting

### PR DESCRIPTION
**Pull request by bond95**
Fixes: https://github.com/oVirt/ovirt-web-ui/issues/809

### CODE REVIEW

**Comment by gregsheremeta** [comment]
ci build please

**Comment by gregsheremeta** [comment]
[need to fix the build]

**Comment by gregsheremeta** [comment]
@bond95 please rebase and run the build

**Comment by bond95** [comment]
ci build please

**Comment by sjd78** [comment]
@samuelmacko - Were you able to successfully verify this PR?

**Pull request merged**
