### PR TITLE
Create VM Wizard - added tooltip message to Disk size field on edit mode

### PR DESCRIPTION
**Pull request by bamsalem**
Fixes: #1216  

The fix related to issue #1214  and PR #1217 , so the changes from PR #1217 can be found in this PR in commit 6bbd3e0.

In the Create VM Wizard > storage step I added tooltip to disk size field.
I used the same message as used in "create new disk" on VM's card.
after the tooltip addition the `FormControl` was too small, so I increased the column width from 10% to 15 % and I removed the last column width value which was 40px, so now the width value is the default value (`auto`).

 before (10% with the new tooltip):
- view mode:
image
- edit mode:
image

after (15%):
- view mode:
image
- edit mode:
image

### CODE REVIEW

**Comment by isaranova** [comment]
ci build please

**Comment by isaranova** [comment]
LGTM

**Comment by sjd78** [comment]
@bamsalem - This PR needs to be rebased and the merge conflict resolved.  The conflict is in the width of the action column.  You will probably want to retain the width, but only testing it will verify.

**Comment by bamsalem** [comment]
@sjd78 , resolved.

**Pull request merged**
