### PR TITLE
(deprecated, see #699 instead) VM Edit page redesin

### PR DESCRIPTION
**Pull request by sjd78**
selection_109

This is currently a **Work-In-Progress**, DO NOT MERGE

Addresses redesign #652.

Includes PRs ~~#651~~, ~~#656~~, ~~#657~~, #659,  ~~#673~~, #678, #679, ~~#687~~ and #690 as its base.

As of the last edit, the first 8 commits currently correspond to PRs:
 - #659 &rarr; getRoutes() to fix breadcrumb titles
 - #678 &rarr; flex-box layout
 - #679 &rarr; refactor `ovritapi`
 - #689 &rarr; fix render of on page console buttons (margins and separators)
 - #690 &rarr; better handling for "deep fetch" / linked / sub VM resources
 - #694 &rarr; update `VmStatusIcon` icons and pf-react

### CODE REVIEW

**Comment by gregsheremeta** [comment]
we'll need to carve this PR into smaller ones that can be done within our new 2 week release cycle

**Comment by sjd78** [comment]
@gregsheremeta - the first 5 commits currently correspond to PRs:
 - #659 &rarr; getRoutes() to fix breadcrumb titles
 - #678 &rarr; flex-box layout
 - #679 &rarr; refactor `ovritapi`

09a2a9f can be carved out, but I think the rest should stay together.

**Comment by gregsheremeta** [comment]
> the rest should stay together

problem with that is we'll be releasing every two weeks. They need to be carved so we can take sections and merge them to master and release.

**Comment by sjd78** [comment]
> problem with that is we'll be releasing every two weeks. They need to be carved so we can take sections and merge them to master and release.

I get that, but in this case, each of the individual card commits take the card from the demo text "Card details go here" to at the very least view details.  So if you're ok with each card being "demo text" for awhile on master while the other detail card commits get their own PRs, I could go that way as well.  That approach just seems too fine grained.

**Comment by gregsheremeta** [comment]
> if you're ok with each card being "demo text" for awhile on master

I am :)

> too fine grained

release early, release often :)

**Comment by sjd78** [comment]
>>    if you're ok with each card being "demo text" for awhile on master
> 
> I am :)
> 
>>  too fine grained
> 
> release early, release often :)
>

Perhaps the problem then becomes using a PR like this is a crap way of doing things.  Using a topic in gerrit would be perfect, but that doesn't exist in github.  That's why I started adding PR details to the issue instead.

At least then, I can maintain a branch in my fork that corresponds to the commits for each PR that hasn't been merged yet but is required by my next unit of work. My branch https://github.com/sjd78/ovirt-web-ui/tree/_refactor_collector_ is how I'm doing it now.

**Comment by sjd78** [comment]
> ccb3070 can be carved out

See #690 where I carved out the bits of that commit that did not add statistics to the VMs.  Commit 3ab3a09 strictly adds statistics.

**Comment by gregsheremeta** [comment]
> That's why I started adding PR details to the issue instead.

ok, now I'm confused again. I thought this PR was for Overview card (top left) and so I just edited it, but now it looks like this is for the overall base page.

Maybe we should start with fresh PRs. This is getting gross.

**Comment by sjd78** [comment]
> Maybe we should start with fresh PRs. This is getting gross.

Agreed.  A bunch of new PRs are coming shortly.

**Comment by sjd78** [comment]
This PR is replaced by #699, #700, #701, and #702.

**Pull request closed without merging**
