### PR TITLE
Allow opening a VM console for all console types

### PR DESCRIPTION
**Pull request by hstastna**
**Fixes issue:** https://github.com/oVirt/ovirt-web-ui/issues/1181

This PR makes the VM console work again by adding missing `setVmSessions` function as an action creator. The issue was introduced [here](https://github.com/oVirt/ovirt-web-ui/pull/1174/files#diff-d880421c8f83b5c8225c4a2bb45716c4L341).

In addition, I'm removing unused `SET_VM_CONSOLES`.

Another related PR: https://github.com/oVirt/ovirt-web-ui/pull/204

---

**Before:**
console_before

**After:**
console_after

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by sjd78** [comment]
ci add to whitelist

**Comment by isaranova** [comment]
ci build please

**Comment by isaranova** [comment]
Cannot access browser console, getting disconnected page. Error message:
Screenshot from 2020-05-11 01-42-43

systemctl status ovirt-websocket-proxy.service shows this error:
ovirt-websocket-proxy.py[6998]: ovirt-websocket-proxy[7577] INFO msg:871 handler exception: 'token'

**Comment by sgratch** [comment]
> Cannot access browser console, getting disconnected page. Error message:
> Screenshot from 2020-05-11 01-42-43

@hstastna Can you please check why VNC browser console fails? It's reproduced to me as well.

**Comment by sgratch** [comment]
This was merged so that at least Spice and VNC (non browser) consoles will work on coming build. A separate PR for the browser console problem will be opened if needed.

**Comment by sgratch** [comment]
Now that this was merged, testing it can be done from the master branch build artifacts CI: https://jenkins.ovirt.org/job/oVirt_ovirt-web-ui_standard-on-ghpush/lastSuccessfulBuild/artifact

**Pull request merged**
