### PR TITLE
Revert "Add Events view"

### PR DESCRIPTION
**Pull request by sgratch**
Reverts oVirt/ovirt-web-ui#1592

Due to few functional aspects of this solution, specifically concerning permissions and info that the user shouldn't been exposed to. Let's re-think about a better solution for this for next release. Since it's a new functionality, there is no problem with reverting for now

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Review by sjd78 — APPROVED** [review]
LGTM

VM event view is gona and I see no UI or console errors.

**Pull request merged**
