### PR TITLE
"Force" shut down action added

### PR DESCRIPTION
**Pull request by mareklibra**
With this patch, the user can shut down a VM in either "polite" or "force" way.

Action confirmation dialog changed to bootstraps' popover.

Fixes: https://github.com/oVirt/ovirt-web-ui/issues/16

confirmation

### CODE REVIEW

**Comment by mareklibra** [comment]
@jelkosz, @bond95, @matobet What do you think about using such a component for user confirmation?

The component can be either two-state Yes-No or three-state Yes-No-Extra.

CSS needs to be polished.

yesnopopover

**Comment by mykaul** [comment]
Cancel should be in the middle to prevent accidental click on force, unless
there's confirmation.

**Comment by mareklibra** [comment]
Done - "Cancel" button is rendered in the middle

**Comment by mareklibra** [comment]
Text color is inherited.
New confirmation component is used for: Shutdown, Reset, Suspend

**Pull request merged**
