### PR TITLE
Filter header for admin users

### LINKED ISSUE #317: configurable "filtered" view
We changed the behavior of the old portal to show all the VMs user has access to (all returned by REST API). But this is not a great behavior for everyone. Sometimes people have to use an admin permission for otherwise regular user to allow some specific operation in webadmin. But it doesn't mean user should see/access all the VMs, at least not in an obvious way (since he/she can't run them anyway)
Let's ake the behavior configurable on the server side, something like "Display only VMs with UserVM permission" option

### PR DESCRIPTION
**Pull request by jniederm**
fixes #317

---
This change is [Reviewable](https://reviewable.io/reviews/ovirt/ovirt-web-ui/398)

### CODE REVIEW

**Comment by michalskrivanek** [comment]
*[src/ovirtapi.js, line 14 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZt2NJbBhTlcc9Rljl:-KyZt2NJbBhTlcc9Rljm:bdxsso5) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L14)):*
> ```JavaScript
> type InputRequestType = { url: string, input: string, contentType?: string }
> type VmType = { vm: Object }
> type OptionVersionType = '3.6' | '4.0' | '4.1' | '4.2' | 'general'
> ```

bleh, can we avoid a list of versions? Use the cluster version perhaps?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by mareklibra** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/ovirtapi.js, line 14 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZt2NJbBhTlcc9Rljl:-KyZynpFxylgJ3jlsEAd:bt1b35) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L14)):*
<details><summary><i>Previously, michalskrivanek wrote…</i></summary><blockquote>

bleh, can we avoid a list of versions? Use the cluster version perhaps?
</blockquote></details>

IIUC, the only effective use of OptionsVersionType is recently within the fetchPermissionWithoutFilter() generator function.

Please note, web-ui requires oVirt API >= 4.0 (see version.js.in).

I think, it's fine to check for "string" only.
Anyway, if such a check is required, let's do it by
 - use of constants
 - version enumeration within generated file, like the version.js.in

This will avoid a lot of pain in the future.

---

*[src/ovirtapi.js, line 660 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZvEZ6DwxbjqnHW7Ci:-KyZvEZ6DwxbjqnHW7Cj:b-yk2bda) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L660)):*
> response.values.system_option_value

Please consider the case of malformed API output.

---

*[src/ovirtapi.js, line 661 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZwsI2Iz1gX-ewDaVy:-KyZwsI2Iz1gX-ewDaVz:b7s0ipd) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L661)):*
> { value: string, version: OptionVersionType }

This is not checked at runtime

---

*[src/ovirtapi.js, line 663 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZx3tRCD2fF83RYfbF:-KyZx3tRCD2fF83RYfbG:bsujeq5) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L663)):*
> ```JavaScript
>           .filter((valueAndVersion: { value: string, version: OptionVersionType }) => valueAndVersion.version === version)
>           .map(valueAndVersion => valueAndVersion.value)[0]
>         return result === undefined ? null : result
> ```

please do useful logDebug() if missing

---

*[src/saga/login.js, line 207 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZy0swptZYuvaYCw3B:-KyZy0sx-rNT2q65vKvl:b-6qzsk) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/saga/login.js#L207)):*
> ```JavaScript
>   const alwaysFilterOption = yield callExternalAction(
>     'getOption',
>     Api.getOption, {
> ```

Please wrap action creation in an action creator method for consistency

---

*[src/saga/login.js, line 216 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZyRnrZhYu21ZNAY7I:-KyZyRnrZhYu21ZNAY7J:bvug5wn) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/saga/login.js#L216)):*
> alwaysFilterOptionTrue

please name it: isAlwaysFilterOption

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by jniederm** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/ovirtapi.js, line 14 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZt2NJbBhTlcc9Rljl:-Kya3y1p55VFlUZYCy06:bjybo7c) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L14)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

IIUC, the only effective use of OptionsVersionType is recently within the fetchPermissionWithoutFilter() generator function.

Please note, web-ui requires oVirt API >= 4.0 (see version.js.in).

I think, it's fine to check for "string" only.
Anyway, if such a check is required, let's do it by
 - use of constants
 - version enumeration within generated file, like the version.js.in

This will avoid a lot of pain in the future.


</blockquote></details>

This a Flow type annotation that provides compile time checking (not applied in this particular case) and is removed in runtime.

It is here to improve UX when using IDE, to give developer a hint what values are expected and highlights problem if wrong value is passed. (constant wouldn't help here)

Values don't relate to engine/api version nor to cluster/compatibility version directly. It's rather values of `vdc_options.version` column.  (generated enumeration wouldn't help here)

If a developer will want to use other version, e.g. '4.3' in the future, it can be easily added to the type.

I there any possible problem I'm missing?

 

---

*[src/ovirtapi.js, line 661 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZwsI2Iz1gX-ewDaVy:-Kya9zG2_NpTwSMhLrS8:b-l2v78y) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L661)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

> { value: string, version: OptionVersionType }

This is not checked at runtime
</blockquote></details>

Yes, it's here to improve readability. I guess not everyone structure of the api response.

---

*[src/ovirtapi.js, line 663 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZx3tRCD2fF83RYfbF:-KyaAFjHNR7NfvSudV_c:b-896fix) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L663)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

please do useful logDebug() if missing
</blockquote></details>

Done.

---

*[src/saga/login.js, line 207 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZy0swptZYuvaYCw3B:-Kya3UEzC85sF_Cdv-bC:b-896fix) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/saga/login.js#L207)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

Please wrap action creation in an action creator method for consistency
</blockquote></details>

Done.

---

*[src/saga/login.js, line 216 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZyRnrZhYu21ZNAY7I:-Kya3ZSltOZUjaGrqkis:b-896fix) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/saga/login.js#L216)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

> alwaysFilterOptionTrue

please name it: isAlwaysFilterOption
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by jniederm** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/ovirtapi.js, line 660 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZvEZ6DwxbjqnHW7Ci:-KyaBT2aMzIOHm1OqC0E:b-xgw5k2) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L660)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

> response.values.system_option_value

Please consider the case of malformed API output.

</blockquote></details>

`TypeError` exception will be throw here, caught in `callExternalAction()` function and the client will be passed an object of one property `error` that will be the TypeError instance. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by mareklibra** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/ovirtapi.js, line 14 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZt2NJbBhTlcc9Rljl:-KyaBIzZiM12ONR2AJ9Z:b-rlfl70) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L14)):*
I think its neither handy handy nor readable to rely on static code checker in this.

> It is here to improve UX when using IDE, to give developer a hint what values are expected and highlights problem if wrong value is passed. (constant wouldn't help here)

I think readability and IDE support will be much improved by constants instead of this.

>  (generated enumeration wouldn't help here)

I meant to keep possible values at one place, possibly generate them. But this is not crucial.

---

*[src/ovirtapi.js, line 660 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZvEZ6DwxbjqnHW7Ci:-KyaDDSk8_XcFlzCAfX1:b-a6v1ue) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L660)):*
<details><summary><i>Previously, jniederm wrote…</i></summary><blockquote>

`TypeError` exception will be throw here, caught in `callExternalAction()` function and the client will be passed an object of one property `error` that will be the TypeError instance. 
</blockquote></details>

In my opinion, the application should not fail on accessing props of `undefined`.
I would log the error and use default or null (better)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by mareklibra** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/ovirtapi.js, line 661 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZwsI2Iz1gX-ewDaVy:-KyaDYK_lVp9VwtR7qK2:bjfe0r2) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L661)):*
<details><summary><i>Previously, jniederm wrote…</i></summary><blockquote>

Yes, it's here to improve readability. I guess not everyone structure of the api response.
</blockquote></details>

Exactly. This is useless, never called, boilerplate. I would not rely on the Flow so much if there are much simpler constructs in the language itself

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by mareklibra** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/saga/login.js, line 212 at r2](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyaMV88huz1v4AI0rWc:-KyaMV88huz1v4AI0rWd:b-yulu6h) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/7c545f2c58cd9543e87c11c873a1e9d721749aa4/src/saga/login.js#L212)):*
> ```JavaScript
> 
>   if (alwaysFilterOption.error) {
>     put(setUserFilterPermission(false))
> ```


yield put

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by mareklibra** [comment]
Review status: 0 of 3 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/actions/index.js, line 107 at r2](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyaOovBsIeMMzaHHg4l:-KyaOovCXwA6uXJpxcNt:b-ol4n5t) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/7c545f2c58cd9543e87c11c873a1e9d721749aa4/src/actions/index.js#L107)):*
> getOption
Action creator must have `type`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by jniederm** [comment]
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/ovirtapi.js, line 14 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZt2NJbBhTlcc9Rljl:-KyawMFqXnFTO1NMmXr0:blcij38) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L14)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

I think its neither handy handy nor readable to rely on static code checker in this.

> It is here to improve UX when using IDE, to give developer a hint what values are expected and highlights problem if wrong value is passed. (constant wouldn't help here)

I think readability and IDE support will be much improved by constants instead of this.

>  (generated enumeration wouldn't help here)

I meant to keep possible values at one place, possibly generate them. But this is not crucial.
</blockquote></details>

I hope we'll agree on something that bring us Java-like comfort while coding.

---

*[src/ovirtapi.js, line 660 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZvEZ6DwxbjqnHW7Ci:-KyawnLA0JKIL6y2UIwx:bwae5i9) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L660)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

In my opinion, the application should not fail on accessing props of `undefined`.
I would log the error and use default or null (better)
</blockquote></details>

`defaultValue` argument added. If the argument provided, returned promise will never be rejected.

---

*[src/ovirtapi.js, line 661 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZwsI2Iz1gX-ewDaVy:-Kyax0-KmOMfLb764P7m:be3uizi) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L661)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

Exactly. This is useless, never called, boilerplate. I would not rely on the Flow so much if there are much simpler constructs in the language itself
</blockquote></details>

Yes, it never called. But I still wouldn't call type annotations a boilerplate.

---

*[src/actions/index.js, line 107 at r2](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyaOovBsIeMMzaHHg4l:-KyazSz9QqA2AY3HhLFe:b-896fix) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/7c545f2c58cd9543e87c11c873a1e9d721749aa4/src/actions/index.js#L107)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

> getOption
Action creator must have `type`
</blockquote></details>

Done.

---

*[src/saga/login.js, line 212 at r2](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyaMV88huz1v4AI0rWc:-KyazXll8qQ9Cjup9f3P:b-896fix) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/7c545f2c58cd9543e87c11c873a1e9d721749aa4/src/saga/login.js#L212)):*
<details><summary><i>Previously, mareklibra (Marek Libra) wrote…</i></summary><blockquote>

yield put
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by mareklibra** [comment]
Review status: 0 of 4 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/ovirtapi.js, line 653 at r3](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyjaSO_c6TLZlKsCTMI:-KyjaSO_c6TLZlKsCTMJ:bbhj4pt) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/9193085ea07dea8cc3f72b573868b677343e5a7b/src/ovirtapi.js#L653)):*
> rawPromise 

I prefer well done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by mareklibra** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Comment by mareklibra** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/ovirtapi.js, line 14 at r1](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398#-KyZt2NJbBhTlcc9Rljl:-KyjcIZ2sU1KtINQNIlg:b-hv4112) ([raw file](https://github.com/ovirt/ovirt-web-ui/blob/a0ab3e51780771452aea331c03da0f7de371cbdc/src/ovirtapi.js#L14)):*
<details><summary><i>Previously, jniederm wrote…</i></summary><blockquote>

I hope we'll agree on something that bring us Java-like comfort while coding.
</blockquote></details>

It would be great, but I do not prefer to do so by such tool like Flow.
I would rather go standard javascript way to achieve that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/ovirt/ovirt-web-ui/398)*

**Pull request merged**
