### PR TITLE
Create VM - add close confirmation to the wizard

### PR DESCRIPTION
**Pull request by bamsalem**
Fixes: #1231 

Hi I changed the behavior of the create VM Wizard. before the changes the dialog have been closed  without confirmation in case of:
1. root click.
2. hitting Esc.
3. click on the "X" button.
4. click on "cancel" button.
from now on on hitting Esc and root click the dialog will ignore the hitting/click, and in case of clicking on "X"/ "cancel" button new dialog will appear if edits have been made, if no edits were made the Wizard will be closed without confirmation.
the purpose of this dialog is to confirm that the user wants to leave the Wizard.
dialog's screenshot:
image

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by sjd78** [comment]
@bamsalem - Please try to use the `NavigationConfirmationModal` component so the "do you want to exit with unsaved changes" dialog can remain consistent across the app.

**Comment by bamsalem** [comment]
I made a few changes according to @sjd78 review, so it looks different:
image
@rszwajko @hstastna 
WDYT?

**Comment by sjd78** [comment]
> It works well, I'm just not sure about how it should look like. Because for example in some other situation, when I try to remove some VM, I can see slightly different design (without exclamation mark or any orange color). And it's some kind of warning, too.
> dialog

The style being used right now is using the same dialog that is used on the details page.  So it is consistent there.  I'm good with how it looks.

**Comment by isaranova** [comment]
ci build please

**Comment by isaranova** [comment]
LGTM

**Comment by hstastna** [comment]
@yfrimanm I know this PR has already been merged but I would like to know your opinion. See [this comment](https://github.com/oVirt/ovirt-web-ui/pull/1239#pullrequestreview-455700975). Thanks a lot! :sparkle:

**Comment by sgratch** [comment]
> I think both dialogs have the role to inform the user about doing something sensitive regarding losing some data/information. So I think they should look the same.

@hstastna I think that there is a difference between those two dialogs so it's ok that they are differ:
The first dialog includes a warning about unsaved changes (the same style as implemented in this PR) and the second one is more about approval for removing a VM which is a non-rollback action. That's why the "remove" button is also in red. There is a difference between unsaving non applied data to removing an existing VM.

**Comment by yfrimanm** [comment]
Hi Ovirt/Ovirt-Web-Ui, https://github.com/hstastna, +Sharon Gratch
<sgratch@redhat.com>

I think it makes sense to use this pattern. But I wonder if for the unsaved
changes modal - the primary action button should be to the left of the
secondary action button. In other words, the  buttons will switch sides so
the 'Yes' will be on the left and the 'No' will be on the right side.

+Matthew Carleton <mcarleto@redhat.com> WDYT?

**Comment by sgratch** [comment]
> Hi Ovirt/Ovirt-Web-Ui, https://github.com/hstastna, +Sharon Gratch <sgratch@redhat.com> I think it makes sense to use this pattern. But I wonder if for the unsaved changes modal - the primary action button should be to the left of the secondary action button. In other words, the buttons will switch sides so the 'Yes' will be on the left and the 'No' will be on the right side. +Matthew Carleton <mcarleto@redhat.com> WDYT?

@yfrimanm @hstastna This is a good point. I actually noticed that all our **old** GWT/webadmin dialogs are following this rule of  'Yes' button on the left and the 'No' button is on the right side.
For some reason, all the **latest** react dialogs on both web-ui and webadmin/ui-extensions were designed (AFAIR by Laura) such that the primary action button is located on the right. 
I thought it was related to Patternfly guidelines...

**Comment by sgratch** [comment]
@bamsalem I found out another thing related to this fix that is a bit annoying:
When displaying the "review report" step after the VM was already created and there is no data that the user can lose by exiting the dialog:
image

Then the user can exit without viewing the VM in two ways:
Clicking the "Close" button - which works 
Or clicking the "x" button - which popup the "closing confirmation" dialog - this seems wrong,

**Comment by hstastna** [comment]
@sjd78 WDYT about [this](https://github.com/oVirt/ovirt-web-ui/pull/1239#issuecomment-676416329)? Thanks! :)

**Comment by sjd78** [comment]
> > Hi Ovirt/Ovirt-Web-Ui, https://github.com/hstastna, +Sharon Gratch [sgratch@redhat.com](mailto:sgratch@redhat.com) I think it makes sense to use this pattern. But I wonder if for the unsaved changes modal - the primary action button should be to the left of the secondary action button. In other words, the buttons will switch sides so the 'Yes' will be on the left and the 'No' will be on the right side. +Matthew Carleton [mcarleto@redhat.com](mailto:mcarleto@redhat.com) WDYT?
> 
> @yfrimanm @hstastna This is a good point. I actually noticed that all our **old** GWT/webadmin dialogs are following this rule of 'Yes' button on the left and the 'No' button is on the right side.
> For some reason, all the **latest** react dialogs on both web-ui and webadmin/ui-extensions were designed (AFAIR by Laura) such that the primary action button is located on the right.
> I thought it was related to Patternfly guidelines...

PF4 has Modal buttons to the left, and the primary action button left most: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal

PF3 has Modal buttons to the right, and the primary action button right most: https://www.patternfly.org/v3/pattern-library/forms-and-controls/modal-overlay/#design

Interesting to note that both PF3 & PF4 have the primary action button on the "outside", or closest to the edge.  At least that is consistent.

So with web-ui being mostly PF3 at the moment, the pendulum should probably swing the the PF3 style, right aligned, primary to the right-most / outside.

Tag: @yfrimanm, @hstastna, @sgratch

**Pull request merged**
