### PR TITLE
Render "Loading ..." message when communicating with server

### PR DESCRIPTION
**Pull request by mareklibra**
The user is informed about communication with server when
 - data is being initially loaded
 - waiting for an action
 - load after Refresh button
 - refreshing data when VM detail is opened

Regular polling does not lead to rendering this "Loading ..." message.

Fixes: https://github.com/oVirt/ovirt-web-ui/issues/153

### CODE REVIEW

**Comment by mareklibra** [comment]
@jelkosz , better than screenshots :-)

docker run --rm -it -e ENGINE_URL=https://engine.local/ovirt-engine --net=host -p 3000:3000 mareklibra/ovirt-web-ui-devel:pullrequest_198

**Comment by jelkosz** [comment]
@mareklibra works nice and I feel much more comfortable with the application now.

But Im not a huge fan of the visual part. Some notes there:
- it is a bit too tall - there is a lot of space above and below the text. There should be some, but this is a bit too much.
- the red border around it seems a bit too aggressive. Maybe an orange? Similar to the unknown OS icon's colour?

@jniederm could you please also check?

**Comment by jniederm** [comment]
* Color: I understand that the popup is based on [patternfly alerts](https://www.patternfly.org/pattern-library/widgets/#alerts) and in general I'd also use class `alert-warning`. However it really feels a bit too red, especially compared to gmail loading info. Maybe we can try `alert-info`. 
gmail loading
* Maybe we can just put a [spinner](http://www.patternfly.org/pattern-library/widgets/#spinner) as a next block to the black top bar, optionally with a label
* If it is supposed to appear also for some long-lasting actions, we can consider label "Working ..." which is more general and covers actions better.

**Comment by mareklibra** [comment]
I don't like alert-info much. I think alert-warning is closer what we are looking for ...
So I adjusted it a little bit, it looks less aggressive now.

For comparison, there's even the spinner which _replaces_ the "Refresh button" if needed.

- Let's choose one of them:
01_bothspinnerandtext


- Spinner tooltip:
02_withtooltip

- No load in progress:
03_noload

**Comment by mareklibra** [comment]
After offline discussion: let's go with the text.

I'm removing the docker image referenced above.

This is the result:
result

**Pull request merged**
