### PR TITLE
Updated Patternfly package to 3.53.1 version

### LINKED ISSUE #747: Update PatternFly to 3.53.1
Update PatternFly to 3.53.1 for new Patternfly features like the latest Message Dialog.

### PR DESCRIPTION
**Pull request by bond95**
This was done for getting new Patternfly features, like Message Dialog.

Fixes #747

### CODE REVIEW

**Comment by gregsheremeta** [comment]
code lgtm
needs QE @leistnerova

**Comment by gregsheremeta** [comment]
snapshot rpm for testing:
https://drive.google.com/open?id=1zII3EFEaI1Es5JKpJT64lSN9nOTWGZM1

**Comment by gregsheremeta** [comment]
cc @StLuke can someone test this? I assigned @leistnerova for now ...

**Comment by StLuke** [comment]
@gregsheremeta we need to include it in sprint if we want to prioritize this

**Comment by gregsheremeta** [comment]
I will close this and replace with https://github.com/gregsheremeta/ovirt-web-ui/commit/87c67f169253940cced18d04a1c82d03eb664358 tomorrow, once new dependencies get through CI

**Comment by gregsheremeta** [comment]
replaced by #758

**Pull request closed without merging**
