### PR TITLE
Read user name, password and domain from env variable

### PR DESCRIPTION
**Pull request by rszwajko**
When launching in dev mode, allow passing user, password and domain
as shell variables.

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by rszwajko** [comment]
Added grouping env variables using dotenv library (in particular using [this advice](https://github.com/motdotla/dotenv#what-happens-to-environment-variables-that-were-already-set))

**Comment by sjd78** [comment]
ci add to whitelist

**Review by sjd78 — CHANGES_REQUESTED** [review]
LGTM (oops, I didn't hit approve)

**Review by sjd78 — APPROVED** [review]
LGTM

**Review by sjd78 — CHANGES_REQUESTED** [review]
Ok - so `dotenv` should be added as a "devDependency" with its current version.  Right now it is only working because `dotenv` is a transitive dependency (at 5.0.1).  We'll probably need to update ovirt-engine-nodejs-modules after that.

**Review by bamsalem — APPROVED** [review]
Except @sjd78 review, LGTM
I like this change :)
Just an idea, we don't must to do it, but it will be nice if we can add `.env.example` file.

**Comment by rszwajko** [comment]
@bamsalem 
> Just an idea, we don't must to do it, but it will be nice if we can add `.env.example` file.
>
IMHO documentation is enough. `.env` files are explicitly excluded from git to prevent accidental commit. If we provide an example file then someone might modify it and commit by mistake.

**Review by sjd78 — APPROVED** [review]
LGTM

**Pull request merged**
