### PR TITLE
Recover after rejected fullscreen request

### PR DESCRIPTION
**Pull request by rszwajko**
Fullscreen request can be rejected due to various reasons. In such
case the isFullScreen flag needs to be cleared to synchronize the state
and the displayed UI.

Note that fullscreen request cannot be triggered automatically on page
load. Due to security reasons the API is restricted to user gestures.
This prevents opening the console automatically in full screen when
accessed directly via the link (i.e. by page refresh).

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Review by sjd78 — APPROVED** [review]
LGTM

**Comment by isaranova** [comment]
LGTM

**Comment by ovirt-infra** [comment]
Some tests failed

**Pull request merged**
