### PR TITLE
 Hosts state lifted one level up 

### PR DESCRIPTION
**Pull request by jniederm**
Only the last commit is relevant. The rest is to express dependency on #626 

---

/hosts/hosts -> /hosts because there isn't any other property at level
/hosts any more. Previously there was /hosts/loadInProgress.

ADD_HOSTS and REMOVE_MISSING_HOSTS actions replaced by single
SET_HOSTS since they always (once) occured together.

---
This change is [Reviewable](https://reviewable.io/reviews/ovirt/ovirt-web-ui/627)

### CODE REVIEW

**Comment by sjd78** [comment]
Rebase now that #621 is merged and LGTM.

Looks like it's unique enough to be in parallel with #622 and #624 and #626.

**Comment by mareklibra** [comment]
#622 is merged, no conflicts are reported

**Comment by mareklibra** [comment]
@jniederm , what about moving this #627 to #626? Can be merged together ...

**Comment by jniederm** [comment]
Rebased. We can merged only this and omit #626 to get all code in. Or we can use "Rebase and merge" option (see below) on both PRs and it will work smoothly.

image

**Pull request merged**
