### PR TITLE
Fix babel-node, package.json `intl:*` scripts

### PR DESCRIPTION
**Pull request by sjd78**
Fixes: #1485

Add the current `@babel/node` runtime and adjust the presets
everywhere it is used to the current standards.  All of the `intl:*`
scripts now work.

### CODE REVIEW

**Comment by sjd78** [comment]
(needs a pre-seed)

**Comment by sjd78** [comment]
pre-seed: https://gerrit.ovirt.org/c/ovirt-engine-nodejs-modules/+/115827

**Comment by sjd78** [comment]
ci test

**Review by sgratch — APPROVED** [review]
LGTM

**Pull request merged**
