### PR TITLE
Fixed bug with large numbers in memory and disk charts.

### PR DESCRIPTION
**Pull request by bond95**
Fixes: https://github.com/oVirt/ovirt-web-ui/issues/768

image
image

### CODE REVIEW

**Comment by bond95** [comment]
@sjd78 With details card everything alright, no?
image

**Comment by sjd78** [comment]
> @sjd78 With details card everything alright, no?
> image

Yes, the Details card is ok.

I was talking about these bits:
screenshot-engine local dickerson-web com-2018 11 14-08-35-59

For example, I have a VM with 6 1GiB disks thin provisioned disks:
screenshot_2018-11-14 vm portal

**Comment by bond95** [comment]
@lwrigh @gregsheremeta @sjd78 what do you think about this format? 

image

image

image

**Comment by lwrigh** [comment]
@bond95 I think the first format is the most clear since you have the units in both the first and second numbers in the header.

**Comment by bond95** [comment]
@lwrigh my bad, I must explain a bit clearer.

I mean that this images are one format. When available size unit is the same as total size unit it will be hidden, otherwise shown.

**Comment by sjd78** [comment]
@bond95 - LGTM as well!

**Comment by gregsheremeta** [comment]
ci build please

**Comment by gregsheremeta** [comment]
[need to fix the build]

**Comment by sjd78** [comment]
Fixed the merge conflicts.

**Comment by sjd78** [comment]
ci build please

**Comment by leistnerova** [comment]
I've found some little issues
1. 1024M -> 1G
When free space is almost 1G it shows 1024M instead
screenshot from 2018-12-06 18-24-19

2. null
When the allocated space is so small, there is 'null' instead of 'TiB' in donut
screenshot from 2018-12-06 18-30-07

Otherwise it seems to work fine. And these are not common situations, so I'm not against merging this PR and create new issue for them.

**Comment by gregsheremeta** [comment]
> I'm not against merging this PR and create new issue for them.

Thanks, merging. Please do :)

**Pull request merged**
