### PR TITLE
CreateVmWizard Networking step - Fix saving new nic error

### PR DESCRIPTION
**Pull request by bamsalem**
Fixes: #1299 .
The previous syntax includes bug.
I changed Iterator's syntax, now vnic saved successfully

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Review by hstastna — APPROVED** [review]
LGTM, fixes the bug. Looks like we do want to iterate through the properties of the `this.state.editingErrors` object and not its values.

**Review by sjd78 — APPROVED** [review]
Ah yes, iterating over a set of keys in an object!

This way works.  An alternative form would be:
```js
for (const errorValue of Object.values(this.state.editingErrors)) {
  editingErrors = editingErrors || errorValue
}
```

**Review by sgratch — APPROVED** [review]
LGTM
I don't think QE approval is required here since the issue will show up whenever trying to create a new NIC

**Pull request merged**
