### PR TITLE
Allign design of VmDialog with VmDetail

### PR DESCRIPTION
**Pull request by mareklibra**
Fixes: https://github.com/oVirt/ovirt-web-ui/issues/196

### CODE REVIEW

**Comment by mareklibra** [comment]
01_vmdetail
02_editvm
03_newvm

**Comment by mareklibra** [comment]
@jelkosz , @jniederm , @bond95 , @matobet , @michalskrivanek please provide feedback

**Comment by bond95** [comment]
@mareklibra how its looking with smaller window?

**Comment by mareklibra** [comment]
How it looks like with screen width 850px:
res850px


There's minimal guaranteed width.

**Comment by mareklibra** [comment]
Maybe better solution for help:
01_dottedhelp_createnew
02_dottedhelp_detail
03_dottedhelp_detailexpanded

**Comment by mareklibra** [comment]
Recent screenshots, this looks much better:

**Pull request merged**
