### PR TITLE
Changes the notification count badge position

### PR DESCRIPTION
**Pull request by mouracamila**
I added `margin-top: -6px` and change `margin-left: -1px` in order to fix the issue described at #706. This is how it looks:

Screenshot from 2020-02-13 18-11-47

What do you think?

Fixes: #706

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by sjd78** [comment]
ci test

**Comment by sjd78** [comment]
@lwrigh - Does the badge location look a bit high?  It's tricky since the icons also have the caret icons for the dropdown menu indication.  Probably don't want the badge to cover that if possible.

**Comment by lwrigh** [comment]
> @lwrigh - Does the badge location look a bit high? It's tricky since the icons also have the caret icons for the dropdown menu indication. Probably don't want the badge to cover that if possible.

Yeah for this situation I think the badge locations is fine since the caret is there as well and you want enough of a click area for the user to be able to click it easily enough.

**Pull request merged**
