### PR TITLE
Add Vms navigation vertical bar to VmDetail

### PR DESCRIPTION
**Pull request by mareklibra**
Fixes: https://github.com/oVirt/ovirt-web-ui/issues/231

### CODE REVIEW

**Comment by mareklibra** [comment]
@jniederm , this needs design

01_expanded
02_collapsed

**Comment by jniederm** [comment]
I have a preliminary demo https://jsbin.com/petanarovo/1/edit?html,css,output based on patternfly dropdown menu. @mareklibra is it better? Do you want it to be part of this pull request or a followup?

**Comment by mareklibra** [comment]
@jniederm  I would like to merge this PR in good-enough state.

No matter it needs to be polished, I like the idea you proposed. Anyway, the basics are clear. Let me implement it and we can tune details on real example.

**Comment by mareklibra** [comment]
ok, let's compare difference:

after page load, selected VM is marked with dotted border:
01_redesign

with mouse over `suse`:
02_redesign_mouse

**Comment by mareklibra** [comment]
Another attempt: selected VM is highlighted by background color




I think this looks good-enough. Please comment.

**Pull request merged**
