### PR TITLE
Intl: changes initiated by communication with translators

### PR DESCRIPTION
**Pull request by jniederm**

### CODE REVIEW

**Comment by michalskrivanek** [comment]
In multiple places "virtual machines" when it should be singular

**Comment by mareklibra** [comment]
@jniederm , can you please rebase?
Can we squash some changes? (Is there a particular reason to have one commit per single string change?)

**Comment by jniederm** [comment]
Feel free to squash it. (I created multiple commits to stay safe during my work with zanata.)

Let's leave "virtual machines" unnecessary plural to next intl pull.

**Comment by jniederm** [comment]
Latest version:
image
image
image

Please review.

**Pull request merged**
