### PR TITLE
Add devDeps for `flow-bin` and `postcss`

### PR DESCRIPTION
**Pull request by sjd78**
- Add `flow-bin` to enable manual flow checking.  The version added is the last version used by the project.  To run flow, use the command:
```
      yarn flow check
```

  - Explicitly add `postcss` to remove the `yarn install` warning about missing peer dependencies.  This version was already referenced in yarn.lock so no new dependencies have been added.  The error fixed is this one on a yarn install:

```
  warning " > postcss-loader@4.2.0" has unmet peer dependency "postcss@^7.0.0 || ^8.0.1".
```

### CODE REVIEW

**Comment by rszwajko** [comment]
@sjd78 
How about using the newest version ? It seems we need to update nodejs-modules anyway (see build failure)

**Comment by rszwajko** [comment]
not exactly connected with `flow-bin` but nice to fix (if nodejs modules will be updated):
1. add dev dependency `@babel/node` to re-enable `intl:xxx` tasks
2. update `intl:xxx` presets syntax - the one that worked for me is `--presets @babel/env,@babel/flow`

**Comment by sjd78** [comment]
> not exactly connected with `flow-bin` but nice to fix (if nodejs modules will be updated):
> 
>     1. add dev dependency `@babel/node` to re-enable `intl:xxx` tasks
> 
>     2. update `intl:xxx` presets syntax - the one that worked for me is `--presets @babel/env,@babel/flow`

... https://github.com/oVirt/ovirt-web-ui/issues/1485

**Comment by sjd78** [comment]
> @sjd78
> How about using the newest version ? It seems we need to update nodejs-modules anyway (see build failure)

There are some breaking changes in flow from the version used to current.  Plus some of the library types referenced in flow could/will also break with upgrade without being upgraded at the same time.  ImmutableJS is like that.  I don't want to touch those quite yet, just turn flow back on until there is some time for #1452.

**Comment by sjd78** [comment]
Pre-seed: https://gerrit.ovirt.org/c/ovirt-engine-nodejs-modules/+/115817

**Comment by sjd78** [comment]
ci test

**Review by hstastna — COMMENTED** [review]
LGTM, except that after I run `yarn flow check`, I get the error:
```
$ /home/hstastna/oVirt_/ovirt-web-ui/node_modules/.bin/flow check
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/immutable/dist/immutable.js.flow:406:33

SetSeq [1] is incompatible with IndexedSeq [2].

 [2] 387│   static of<T>(...values: T[]): IndexedSeq<T>;
        :
     403│
     404│ declare class SetSeq<T> extends Seq<T,T> mixins SetIterable<T> {
     405│   static <T>(iter?: ESIterable<T>): IndexedSeq<T>;
 [1] 406│   static of<T>(...values: T[]): SetSeq<T>;
     407│ }
     408│
     409│ declare class List<T> extends IndexedCollection<T> {
```

**Comment by sgratch** [comment]
> LGTM, except that after I run `yarn flow check`, I get the error:
> 
> ```
> $ /home/hstastna/oVirt_/ovirt-web-ui/node_modules/.bin/flow check
> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/immutable/dist/immutable.js.flow:406:33
> 
> SetSeq [1] is incompatible with IndexedSeq [2].
> 
>  [2] 387│   static of<T>(...values: T[]): IndexedSeq<T>;
>         :
>      403│
>      404│ declare class SetSeq<T> extends Seq<T,T> mixins SetIterable<T> {
>      405│   static <T>(iter?: ESIterable<T>): IndexedSeq<T>;
>  [1] 406│   static of<T>(...values: T[]): SetSeq<T>;
>      407│ }
>      408│
>      409│ declare class List<T> extends IndexedCollection<T> {
> ```

This seems related to a bug in flow definitions for Immutable. 
Bumping Immutable package version seems to solve this.

**Comment by sjd78** [comment]
> > LGTM, except that after I run `yarn flow check`, I get the error:
> > ```
> > $ /home/hstastna/oVirt_/ovirt-web-ui/node_modules/.bin/flow check
> > Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/immutable/dist/immutable.js.flow:406:33
> > 
> > SetSeq [1] is incompatible with IndexedSeq [2].
> > 
> >  [2] 387│   static of<T>(...values: T[]): IndexedSeq<T>;
> >         :
> >      403│
> >      404│ declare class SetSeq<T> extends Seq<T,T> mixins SetIterable<T> {
> >      405│   static <T>(iter?: ESIterable<T>): IndexedSeq<T>;
> >  [1] 406│   static of<T>(...values: T[]): SetSeq<T>;
> >      407│ }
> >      408│
> >      409│ declare class List<T> extends IndexedCollection<T> {
> > ```
> 
> This seems related to a bug in flow definitions for Immutable.
> Bumping Immutable package version seems to solve this.

This is an old error that we ignored before.  I'm fine with keeping it since flow type checks are purely manual/ide based right now.   

From my answer to Radek's similar question before, seems risky to upgrade flow or immutable.  I'd rather spend time to swap to typescript than fix flow:

> There are some breaking changes in flow from the version used to current. Plus some of the library types referenced in flow could/will also break with upgrade without being upgraded at the same time. ImmutableJS is like that. I don't want to touch those quite yet, just turn flow back on until there is some time for #1452.

**Review by sgratch — APPROVED** [review]
LGTM

**Pull request merged**
