### PR TITLE
Disable the docker container builds on travisci

### PR DESCRIPTION
**Pull request by sjd78**
Due to (1) consistent docker container build problems on travisci,
and (2) container issues to be considered in issue #1442, disable
the docker container build.  Any updates to the docker hub image
will need to be manual until #1442 is resolved.

### CODE REVIEW

**Comment by sjd78** [comment]
@sgratch , @rszwajko , @hstastna - I'd rather see travisci pass with just running the build by itself than keep on failing (most of the time at least) with the docker build included.

**Review by hstastna — APPROVED** [review]
I agree with disabling the docker container build for now.

**Comment by rszwajko** [comment]
I have no opinion on that.

**Comment by sjd78** [comment]
Note: travis-ci.org is no longer running builds, so this PR is a bit of a moot point.  If we want automated container builds, it'll need to be done in std-ci or migrate to travis-ci.com.

**Comment by sgratch** [comment]
ci test

**Comment by sgratch** [comment]
> I'd rather see travisci pass with just running the build by itself than keep on failing (most of the time at least) with the docker build included.

@sjd78 note that now after travis-ci.org is no longer running builds, the travisci is totally dismissed on all PRs except here where it's always pass due to running the build only.
I'm actually not sure what is preferable for now. Let's wait after 4.4.7 is released, check with the community if docker container is ever used and decide.

**Comment by sjd78** [comment]
Closing this PR because travisci.org is not running builds anymore so the change is not required.  Leave #1442 open to track future container deploy work.

**Pull request closed without merging**
