### PR TITLE
Add "Runs on host" info

### PR DESCRIPTION
**Pull request by mareklibra**
Admin user can link-through to Cockpit running on a host with particular VM.

Fixes: https://github.com/oVirt/ovirt-web-ui/issues/117

### CODE REVIEW

**Comment by mareklibra** [comment]
See the hyperlink in the `status` filed:

runonhost

**Comment by mareklibra** [comment]
For longer host name:
01_longername

and narrow screen:
02_narrowscreen

What about rendering the `(on [HOST_NAME])` separately as a first entry of the second column (right above the `Consoles`).
Sort of `Runs on:      [LINK_TO_HOST]`

**Comment by mareklibra** [comment]
Anyway, we shall avoid additional field

**Comment by mareklibra** [comment]
What about this? @jelkosz , @jniederm 
How to rephrase?
hostconsole

**Comment by mareklibra** [comment]
For non-admin user:
nonadmin

**Comment by jelkosz** [comment]
@mareklibra 
 - maybe instead of "On" I would put "Runs on host: ..."
 - the hostname should look like you can click it so you know it you can click it

**Comment by mareklibra** [comment]
runsonhost

**Comment by jelkosz** [comment]
@mareklibra 👍

**Comment by jniederm** [comment]
I have doubts about the tooltip solution. As a new user to webui, how am I supposed to find it? <kbd>Ctrl+F</kbd> couldn't work. I'd prefer regular additional name-value widget.

**Comment by mareklibra** [comment]
Let's try it this way. We can change to name-value solution or something even better later.
The reasons for preferring the per-click context information now are:
- it's a pattern in web-ui to use blue-style of `<a href>` to route and gray-underlined-style to denote local context-aware additional information
- so the user knows the `[status]` can be clicked since the notation is used on other places as well
- I don't think the user will search (like Ctrl+F) for host name on the VmDetail page. It's for a single VM. 
- We might add new `Hosts` tab listing all VMs defined on particular host (+ more host info), if needed. Would be linked from the VmPage as well.
- This cockpit-link is rendered for admin users only (not the "typical" kind of users)
- context information of the `[status]` is used for other kind of information, like `status reason` - see later commit in this PR. So it's not single-purpose.
- the page shall provide sufficient amount of information but not too much to keep it understandable at the first glance. This is sort of "advanced" information and adding extra field for it is overwhelming in my opinion.
- Maybe we will be forced to split the recent layout of VmDetail page to "sort of subtabs or so" in the future. Anyway, I would like to avoid/postpone it as much as possible.

The web-ui is focused on standard, non-admin users. We have to keep the presented information at minimal useful level. For more details, there's webadmin.

**Comment by mareklibra** [comment]
Enriched for status reason (requested in https://github.com/oVirt/ovirt-web-ui/issues/247):
statusreason

**Pull request merged**
