### PR TITLE
Fixed broken grid because of pools

### PR DESCRIPTION
**Pull request by bond95**
FIxed this issue https://github.com/oVirt/ovirt-web-ui/issues/471
@mareklibra please review.

image

---
This change is [Reviewable](https://reviewable.io/reviews/ovirt/ovirt-web-ui/473)

### CODE REVIEW

**Comment by mareklibra** [comment]
Please add commit message describing the issue and its fix, including link to the bug.

**Comment by mareklibra** [comment]
Fixes: #471

**Comment by mareklibra** [comment]
Otherwise LGTM

**Comment by bond95** [comment]
@mareklibra Done.

**Pull request merged**
