### PR TITLE
Disabled delete button on disks and NICs is gray enough

### PR DESCRIPTION
**Pull request by yodem**
Fixes: #977 

Disabled delete button on disks and NICs is as gray as the play button in snapshots.

Snapshots

disks

### CODE REVIEW

**Comment by yodem** [comment]
@lwrigh Can you please check this commit? I cant add you as a reviewer so im tagging you here :)

**Comment by sgratch** [comment]
@lwrigh @yodem 
The issue here is: 
1. Does changing the delete option to a lighter grey in case of a running VM (with a tooltip explaining why removing is disabled) is applied also with PF4 conventions? Currently it's colored in a darker grey
2. If 1 is approved by Laura then I guess we'll need to change it for NICs as well

**Comment by lwrigh** [comment]
> @lwrigh @yodem
> The issue here is:
> 
> 1. Does changing the delete option to a lighter grey in case of a running VM (with a tooltip explaining why removing is disabled) is applied also with PF4 conventions? Currently it's colored in a darker grey
> 2. If 1 is approved by Laura then I guess we'll need to change it for NICs as well

We definitely need some sort of tooltip with an explanation explaining why the button is disabled if the button persists. What exact use case is this for? Does this happen when the VM comes from a pool or is it because of permissions?  

I would avoid applying PF4 to just one button here. If we do one button in PF4 we should do all of them. 

@sgratch @yodem

**Comment by sgratch** [comment]
@lwrigh The scenario is just trying to delete a disk or a NIC for a running VM. 
The current status is that there is a tool-tip and the delete option is disabled as required, but the delete option color is a more darker grey than in other places

**Comment by sgratch** [comment]
Current state:

Screenshot from 2019-08-06 14-38-09

**Comment by sgratch** [comment]
@yodem  please change title to "Disabled delete button on disks **and nics**...."

**Comment by lwrigh** [comment]
> @lwrigh The scenario is just trying to delete a disk or a NIC for a running VM.
> The current status is that there is a tool-tip and the delete option is disabled as required, but the delete option color is a more darker grey than in other places

Okay that makes sense to me.

**Comment by michalskrivanek** [comment]
"can't delete at this time" is not very helpful though....not much different from nothing. I mean...you try and you see that you can't right now do that:) would be better to actually describe why

**Comment by lwrigh** [comment]
> "can't delete at this time" is not very helpful though....not much different from nothing. I mean...you try and you see that you can't right now do that:) would be better to actually describe why

What about "NICs cannot be deleted when the VM is running."?

**Comment by michalskrivanek** [comment]
@lwrigh much better! (if it's true, of course:). Now it explains why and gives a hint to the user what needs to be done

**Comment by sjd78** [comment]
@yodem - This PR needs a rebase (on upstream/master so the commit for "Asleep Changed to Suspended" can be dropped since it already got merged) and commits to be squashed.

**Comment by lwrigh** [comment]
@yodem Could you post current screenshots of it? Thank you!

**Comment by yodem** [comment]
Nothing has seriously changed, besides the tooltip text. 
GrayText

**Comment by lwrigh** [comment]
> Nothing has seriously changed, besides the tooltip text.
> GrayText

Awesome it looks good to me!

**Comment by isaranova** [comment]
LGTM

**Comment by sgratch** [comment]
Verified by QE and therefore can be merged

**Pull request merged**
