### PR TITLE
ux-redesign: VM Details > Disks Card (view only)

### PR DESCRIPTION
**Pull request by sjd78**
View only part of #775 

  - move files to **VmDetails/cards/DisksCard/**

  - view only mode of the Disk Card

  - move src/utils.js to src/utils/index.js

  - export all of the src/utils/*.js functions from the folder's index.js

----
No disks:
screenshot-localhost-3000-2018 09 22-00-10-35

A couple of disks:
screenshot-localhost-3000-2018 09 22-00-11-47

Disk marked bootable:
screenshot-localhost-3000-2018 09 22-00-14-23

In context of the VM Details dashboard:
screenshot-localhost-3000-2018 09 22-00-12-33

### CODE REVIEW

**Comment by gregsheremeta** [comment]
can you post a verification screenshot?

**Comment by gregsheremeta** [comment]
code lgtm

> move src/utils.js to src/utils/index.js

nothing else was using that yet?

**Comment by sjd78** [comment]
>> move src/utils.js to src/utils/index.js
>
> nothing else was using that yet?

Well....yes things were using it.  But, moving a file **utils.js** to **utils/index.js** does not require changing the import statement.  In other PRs (Details Card in specific), I ended up using more then 1 of the files in **src/utils** and it was annoying to have to import each one on a different line.  So packing it all in the index.js allows for separate files for different bits and allows a single import.  Patterfly uses that approach all over.

**Comment by sjd78** [comment]
@gregsheremeta - Added screenshots to the main description

**Pull request merged**
