### PR TITLE
Fix disk and memory chart units

### PR DESCRIPTION
**Pull request by bond95**
- Added precision for formating bytes, now if value of Disk or Memory will be closer to next unit more then 10 %, it will calculate next unit.
- And if change round precision according to value, if value less then 10, it give sense to show two digit after point, if less then 100 give sense to show only one digit if greater, then without floating part.

Fixes: https://github.com/oVirt/ovirt-web-ui/issues/889

image
image

### CODE REVIEW

**Comment by lwrigh** [comment]
Shouldn't the 'Disk' card include KiB as the units in the text above the donut?

**Comment by bond95** [comment]
@lwrigh no, because this is unused memory, which is approximately 0.99 GiB.

**Comment by leistnerova** [comment]
ci build please

**Comment by leistnerova** [comment]
LGTM

**Pull request merged**
