### PR TITLE
Fix bad tooltip breaking in utilization cards

### PR DESCRIPTION
**Pull request by bond95**
Fixes: https://github.com/oVirt/ovirt-web-ui/issues/766

image
image

### CODE REVIEW

**Comment by gregsheremeta** [comment]
ci add to whitelist

**Comment by gregsheremeta** [comment]
ci build please

**Comment by bond95** [comment]
- https://jenkins.ovirt.org/job/oVirt_ovirt-web-ui_standard-check-pr/210/artifact/build-artifacts.el7.x86_64/ovirt-web-ui-1.5.0-0.20181113gitdd1ff1f.el7.noarch.rpm

- https://jenkins.ovirt.org/job/oVirt_ovirt-web-ui_standard-check-pr/210/artifact/build-artifacts.fc28.x86_64/ovirt-web-ui-1.5.0-0.20181113gitdd1ff1f.fc28.noarch.rpm

**Comment by bond95** [comment]
ci build please

**Comment by bond95** [comment]
- https://jenkins.ovirt.org/job/oVirt_ovirt-web-ui_standard-check-pr/264/artifact/build-artifacts.el7.x86_64/ovirt-web-ui-1.5.0-0.20181130git8e1b8d3.el7.noarch.rpm
- https://jenkins.ovirt.org/job/oVirt_ovirt-web-ui_standard-check-pr/264/artifact/build-artifacts.fc28.x86_64/ovirt-web-ui-1.5.0-0.20181130git8e1b8d3.fc28.noarch.rpm

**Comment by leistnerova** [comment]
LGTM

**Pull request merged**
