### PR TITLE
 Clusters state lifted one level up 

### PR DESCRIPTION
**Pull request by jniederm**
Only the last commit is relevant, the rest is to express dependency on #622 

---

/clusters/clusters -> /clusters because there isn't any other property
at level /clusters any more. Previously there was
/clusters/loadInProgress.

ADD_CLUSTERS and REMOVE_MISSING_CLUSTERS actions replaced by single
SET_CLUSTERS since they always (once) occured together.

---
This change is [Reviewable](https://reviewable.io/reviews/ovirt/ovirt-web-ui/624)

### CODE REVIEW

**Comment by sjd78** [comment]
Rebase now that #621 is merged and LGTM.

Looks like it's unique enough to be in parallel with #622.

**Comment by jniederm** [comment]
>Rebase now that #621 is merged and LGTM.
>
>Looks like it's unique enough to be in parallel with #622.

Unfortunately there is a dependency: both #622 and this patch changes `src/reducers/templates.js`

**Comment by mareklibra** [comment]
#622 is merged now

**Comment by bond95** [comment]
@jniederm rebase, please.

**Comment by jniederm** [comment]
Rebased, it seems like ready to merge.

**Pull request merged**
