### PR TITLE
Fixed utilization card responsiveness bug

### PR DESCRIPTION
**Pull request by bond95**
Fixes: https://github.com/oVirt/ovirt-web-ui/issues/765

peek 2019-01-28 13-05

### CODE REVIEW

**Comment by gregsheremeta** [comment]
all @sjd78 and @lwrigh on this one :)

**Comment by bond95** [comment]
@lwrigh I think this discussion is for another PR.

**Comment by sjd78** [comment]
> The fix looks good to me overall. It looks like the VM name and status get lost once the screen reaches a certain size however and that seems like important information to still have available. My one question is would it make sense to put the action buttons into a kebab menu if the screen size reaches a certain, narrow size? @sjd78 What do you think?

@lwrigh - @bond95 is right. Overall VM detail dashboard responsiveness is out of scope for this fix.  This fix focuses on the Utilization card and having the 4 charts reflow and line break nicely.

**Comment by gregsheremeta** [comment]
lgtm. @sjd78 ?

**Comment by leistnerova** [comment]
ci build please

**Comment by leistnerova** [comment]
ci build please

**Comment by leistnerova** [comment]
LGTM

**Pull request merged**
