### PR TITLE
Expire translations after zanata push

### PR DESCRIPTION
**Pull request by sjd78**
After merging PRs and pushing their string changes, pull the
translations.  This picks up translation invalidations (English text
has changed), helping to make sure the translations are not wrong.

PRs to consider:
  - https://github.com/oVirt/ovirt-web-ui/pull/1533
  - https://github.com/oVirt/ovirt-web-ui/pull/1537
  - https://github.com/oVirt/ovirt-web-ui/pull/1539
  - https://github.com/oVirt/ovirt-web-ui/pull/1540
  - https://github.com/oVirt/ovirt-web-ui/pull/1543
  - https://github.com/oVirt/ovirt-web-ui/pull/1549
  - https://github.com/oVirt/ovirt-web-ui/pull/1564
  - https://github.com/oVirt/ovirt-web-ui/pull/1584
  - https://github.com/oVirt/ovirt-web-ui/pull/1585
  - https://github.com/oVirt/ovirt-web-ui/pull/1592

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Review by rszwajko — APPROVED** [review]

**Pull request merged**
