### PR TITLE
Vizualize VmType

### PR DESCRIPTION
**Pull request by mareklibra**
Label denoting VM's type is displayed on VmDetail.
Handles `Desktop, Server, HighPerformance`.
    
Depends on not yet merged https://gerrit.ovirt.org/#/c/77961
Fixes: https://github.com/oVirt/ovirt-web-ui/issues/239

### CODE REVIEW

**Comment by mareklibra** [comment]
01_vmtype
02_vmtype

**Comment by mareklibra** [comment]
I think concept of `labels` is fine for this purpose.
@jniederm , would you change styling of them? Colors?

**Comment by jniederm** [comment]
I'd visualize it just like other regular properties (for example State or Description) because

* there already are two types of label in the engine (standard and SLA ones) and a time may come when we will need to visualize these
* a time may come when we will need to change or set "Optimized for" property in edit/new pages. In such situation it will be natural to visually just replace a text by a dropdown.

**Comment by mareklibra** [comment]
Right, this makes sense.

**Comment by mareklibra** [comment]
01_vmtype
02_vmtype

**Comment by mareklibra** [comment]
@jniederm , what do you think?

**Comment by mareklibra** [comment]
Cc @sgratch

**Comment by sgratch** [comment]
Looks very good to me. 
Few small comments to consider:
1. desktop->Desktop (capitalize the first letter).
2. Consider locating this property under/after the 'Template' property, since changing the Template may change the 'Optimized For' value since it is inherited from it (the properties displaying order has some logic I guess..)
3. What about displaying this property also for Templates now or in the future?

**Comment by mareklibra** [comment]
@sgratch , thanks
1. Done
2. Done
3. Good point, we will think about it when adding Templates view

**Comment by mareklibra** [comment]
01_vmtype

**Comment by mareklibra** [comment]
Merging since agreed otherwise

**Pull request merged**
