### PR TITLE
About modal - externalize app & api version text

### PR DESCRIPTION
**Pull request by sjd78**
Resolves: #1106

- Externalized:
  - App name
  - Version text
  - API version text
 - Removed extra right margin padding on `<strong>` tags

Base English About dialog after the change:
screenshot-ghost local dickerson-web com_3000-2020 08 18-23_12_57

Dummy (locale=aa) translation dialog after the change:
screenshot-ghost local dickerson-web com_3000-2020 08 18-23_18_27

Text that is highlighted is part of branding and cannot be translated:
screenshot-ghost local dickerson-web com_3000-2020 08 18-23_13_27

### CODE REVIEW

**Review by bamsalem — APPROVED** [review]
LGTM

**Review by hstastna — APPROVED** [review]
LGTM. And I like that with this change, links to _Documentation_ and _Github Issue Tracker_ are bold.

**Comment by isaranova** [comment]
The words "Version" and "API Version" are not translated.
Screenshot_2020-09-01 VM Portal(1)

Czech translation is incomplete:
Screenshot_2020-09-01 VM Portal(4)

French translation starts with a small letter in the "For further information see..." part.
Screenshot_2020-09-01 VM Portal

**Comment by sjd78** [comment]
@isaranova - The actual translations won't appear until the translation group updates everything.  A translation cycle may not happen for awhile.  At this point, the only way to see a "translated" dialog is to run `yarn intl:dummy`, then run in dev mode and open the url like `http://localhost:3000?locale=aa`.

In summary, the about dialog is translatable with this PR, but won't be translated into any specific language until someone other than us updates that language's translations.

**Comment by isaranova** [comment]
> @isaranova - The actual translations won't appear until the translation group updates everything. A translation cycle may not happen for awhile. At this point, the only way to see a "translated" dialog is to run `yarn intl:dummy`, then run in dev mode and open the url like `http://localhost:3000?locale=aa`.
> 
> In summary, the about dialog is translatable with this PR, but won't be translated into any specific language until someone other than us updates that language's translations.

Sorry, I thought the translations were included.
In that case, everything seems to be working as intended.

LGTM

**Pull request merged**
