### PR TITLE
Add new NIC type "e1000e" for oVirt 4.5

### LINKED ISSUE #1586: Missing VNIC Type "e1000e" on VM Portal for oVirt 4.5
Feature enhancement request:

With the newly released oVirt 4.5, a new NIC Type "e1000e" has been added.

> BZ 2033185 [RFE] Add e1000e driver on cluster level >=4.7
> Add e1000e VM Nic type for cluster level 4.7. The e1000 is depracated from RHEL8.0 and users should switch to e1000e when possible.
> https://www.ovirt.org/release/4.5.0/

But this NIC type does not appear to be selectable in VM Portal. Users have to use Admin Portal to switch the type of the NIC to  "e1000e".

I've tested on oVirt 4.5.0.4-1.el8 (with bundled `ovirt-web-ui-1.8.1-1.el8.noarch`). As e1000 is deprecated in some OSes, it would be great if e1000e will be available in VM Portal as well.

image

### PR DESCRIPTION
**Pull request by kurokobo**
Fixes #1586 

Add new NIC type "e1000e" which newly added in oVirt 4.5.

image

Tested this PR on `ovirt-engine-4.5.0.4-1.el8.noarch` as follows:

1. Create new VM which has `e1000` NIC using Admin Portal image
2. Build and start VM Portal including this PR and modify NIC type to `e1000e` image
3. Ensure that the type has changed to `e1000e` on Admin Portal image
4. Create new VM which has `e1000e` NIC using VM Portal 
image
5. Ensure that new NIC has `e1000e` type on Admin Portal 
image

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by kurokobo** [comment]
@sjd78 
Hi, thanks for developing useful Web UI for users! I'm tagging you because it seems that you're working on this project.
This is the first time to send PR to this project, so I'd like to request your review. If there are any concerns or suggestions, please let me know.

Of course it's ok to reject this if I'm on the wrong way. Thanks in advance!

**Comment by kurokobo** [comment]
@sjd78 
Hi, thanks for reviewing! I've added the commit to revert the changes on `src/intl/translated-messages.json` and requested your re-review.
It would be great if you could check again. Thanks!

**Review by sjd78 — APPROVED** [review]
LGTM

**Comment by kurokobo** [comment]
@sjd78
Hi, thanks for reviewing again and approing this. Sorry for bothering you but please let me know if I should do something like run `ci test please` here. Is it ok to just wait this to be merged? Thanks in advance!

**Review by michalskrivanek — COMMENTED** [review]
per https://bugzilla.redhat.com/show_bug.cgi?id=2033185 e1000e is added only to cluster level 4.7 with q35. Here you allow it for everything. It may not be worth extra checks though, so i'm fine with this as is

**Comment by sjd78** [comment]
> per https://bugzilla.redhat.com/show_bug.cgi?id=2033185 e1000e is added only to cluster level 4.7 with q35. Here you allow it for everything. It may not be worth extra checks though, so i'm fine with this as is

That makes sense.  In the case where an invalid type is selected when trying to add a Nic to a VM, the add will fail and the following notification will be shown:
screenshot-localhost_3000-2022 05 26-10_18_32

**Comment by isaranova** [comment]
LGTM

**Pull request merged**
