### PR TITLE
Update VM name filter to match anywhere in the VM name

### PR DESCRIPTION
**Pull request by bamsalem**
hi I just change the filter methods from startsWith to includes.

Fixes: #1127

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by sgratch** [comment]
ci add to whitelist

**Comment by sjd78** [comment]
@bamsalem - Just an FYI, putting "Fixes: XXX" or "Resolves: XXX" ties the PR to the Issue.  Then when the PR is finalized and merged, the issue will be closed automatically.  I made that change already.

It would also be nice to make the PR's description a bit more detailed.  For example:  _VM filtering was using `startsWith()` when matching the filter string to the VM name.  Changing to use `includes()` will produce matches in a more typical way.  In future, if more advanced filtering is needed, a glob and/or regex pattern may be adopted._

**Comment by sgratch** [comment]
Now that this was merged, testing can be done from the master branch build artifacts CI: https://jenkins.ovirt.org/job/oVirt_ovirt-web-ui_standard-on-ghpush/lastSuccessfulBuild/artifact

**Comment by isaranova** [comment]
LGTM

**Pull request merged**
