### PR TITLE
Changed style of select boxes, according to webadmin

### PR DESCRIPTION
**Pull request by bond95**
@mareklibra Please review https://github.com/oVirt/ovirt-web-ui/issues/242

### CODE REVIEW

**Comment by bond95** [comment]
@mareklibra @jniederm Please review
screenshot from 2017-07-28 12-36-14

**Comment by bond95** [comment]
screenshot from 2017-07-28 12-39-26

**Comment by mareklibra** [comment]
not exactly 1:1 with webadmin but I believe good enough 👍

**Comment by jniederm** [comment]
@bond95 please comment https://github.com/oVirt/ovirt-web-ui/pull/297#discussion_r129921979

I find the center text alignment distracting, but except for comment above, it's good to merge.

**Comment by bond95** [comment]
@jniederm fixed ids

**Pull request merged**
