### PR TITLE
Fixed checkbox size in Remove VM confirmation dialog

### PR DESCRIPTION
**Pull request by bond95**
Fixes: https://github.com/oVirt/ovirt-web-ui/issues/975

image

### CODE REVIEW

**Comment by lwrigh** [comment]
Would we be able to change the 'Yes' button to a red destructive button that says 'Remove' since it's a destructive action?

**Comment by bond95** [comment]
> Would we be able to change the 'Yes' button to a red destructive button that says 'Remove' since it's a destructive action?

Yes, but I think this is for another issue, because color of button is not related to this issue.

**Comment by lwrigh** [comment]
> > Would we be able to change the 'Yes' button to a red destructive button that says 'Remove' since it's a destructive action?
> 
> Yes, but I think this is for another issue, because color of button is not related to this issue.

That works for me. I can open up an issue for the remove button.

**Comment by bond95** [comment]
> > > Would we be able to change the 'Yes' button to a red destructive button that says 'Remove' since it's a destructive action?
> > 
> > 
> > Yes, but I think this is for another issue, because color of button is not related to this issue.
> 
> That works for me. I can open up an issue for the remove button.

It would be nice, thank you. =)

**Comment by bond95** [comment]
> Thoughts on just killing this `Checkbox` and use only the one from patternfly-react in the remove VM confirm dialog? As far as I can tell, the remove VM confirm is the only place where this component is use web-ui.

Yes, remove confirmation is the only place, because we don't use anywhere else checkbox at all. But this is discussion for separate issue. This issue little bit not about removing checkbox =)

**Comment by sjd78** [comment]
> > Thoughts on just killing this `Checkbox` and use only the one from patternfly-react in the remove VM confirm dialog? As far as I can tell, the remove VM confirm is the only place where this component is use web-ui.
> 
> Yes, remove confirmation is the only place, because we don't use anywhere else checkbox at all. But this is discussion for separate issue. This issue little bit not about removing checkbox =)

Why would it need a separate issue?  The issue is to fix the render of the checkbox right?  Remove the crap check box, use the patternfly-react one, kill the CSS tweak you had to make and done.  That is cleaner than tweaking a component that doesn't need to even exist anymore.

**Comment by sjd78** [comment]
@bond95 - Any followup?

**Comment by bond95** [comment]
Replaced checkbox @lwrigh @sjd78  
image

**Comment by isaranova** [comment]
ci build please

**Comment by leistnerova** [comment]
ci build please

**Comment by isaranova** [comment]
LGTM

**Pull request merged**
