### PR TITLE
"About" dialog added

### PR DESCRIPTION
**Pull request by mareklibra**
The About dialog renders product name and build version (X.Y.Z-R).
Rendered as modal.

Fixes: https://github.com/oVirt/ovirt-web-ui/issues/89

aboutdialoginvocation

aboutdialogmodal

### CODE REVIEW

**Comment by mareklibra** [comment]
aboutdialoginvocation

aboutdialogmodal

**Comment by mykaul** [comment]
Should be 'Version XYZ' and not 'XYZ Version', no?
Perhaps a link to the project github, to report issues?
Links to documentation?
License?

**Comment by mareklibra** [comment]
@mykaul , thanks for input.

Screenshot updated.
Link to documentation will be added in a follow-up once documentation is ready.
Within https://github.com/oVirt/ovirt-web-ui/pull/132, I will add oVirt API version.

**Comment by mykaul** [comment]
LGTM.

**Pull request merged**
