### PR TITLE
 Operating systems state lifted one level up 

### PR DESCRIPTION
**Pull request by jniederm**
Only the last commit is relevant. The rest is to express dependency on #624.

---

/operatingSystems/operatingSystems -> /operatingSystems because there isn't
any other property at level /operatingSystems any more. Previously there
was /operatingSystems/loadInProgress.

ADD_ALL_OS and REMOVE_MISSING_OSS actions replaced by single
SET_OPERATING_SYSTEMS since they always (once) occured together.

---
This change is [Reviewable](https://reviewable.io/reviews/ovirt/ovirt-web-ui/626)

### CODE REVIEW

**Comment by sjd78** [comment]
Rebase now that #621 is merged and LGTM.

Looks like it's unique enough to be in parallel with #622 and #624.

**Comment by jniederm** [comment]
>Rebase now that #621 is merged and LGTM.
>
>Looks like it's unique enough to be in parallel with #622 and #624.

This depends on #624 because it uses `arrayToMap()`.

**Comment by mareklibra** [comment]
#622 is merged now

**Comment by bond95** [comment]
@jniederm rebase, please.

**Comment by mareklibra** [comment]
#624 is merged now, can you please rebase?

**Comment by jniederm** [comment]
Rebased. In conflictless scenarios GitHub can [do rebase](https://github.com/oVirt/ovirt-web-ui/pull/627#issuecomment-395030990) for us.

**Pull request merged**
